version: '3.8'

services:
  # Frontend CAC
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cac-frontend
    ports:
      - "80:80"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - cac-network

  # Nginx Proxy (opcional - para SSL e proxy reverso)
  nginx-proxy:
    image: nginx:alpine
    container_name: cac-nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-proxy.conf:/etc/nginx/nginx.conf:ro
      # Para SSL certificates (descomente se necessário)
      # - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      frontend:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - cac-network
    profiles:
      - proxy

networks:
  cac-network:
    driver: bridge
    name: cac-network